from __future__ import annotations

# Re-export all public and tested-private symbols from submodules
# to maintain backward compatibility for all importers.
from .approval import (
    DEFAULT_SESSION_GRANT_TTL_HOURS,
    cli_approval_handler,
    make_cli_approval_handler,
    make_cli_budget_prompt_handler,
    run_result_payload,
)
from .automation import (
    _automation_draft_from_args,
    _automation_health,
    _automation_is_running,
    _automation_tick,
    _reconcile_automation_runs,
    _run_automation_once,
    _start_automation_background_run,
    automation_add_command,
    automation_delete_command,
    automation_list_command,
    automation_pause_command,
    automation_promote_command,
    automation_resume_command,
    automation_run_command,
    automation_serve_command,
    automation_show_command,
    automation_status_command,
    automation_template_command,
    automation_tick_command,
)
from .config import _resolve_auto_compact
from .experiment import _execute_parallel_experiment
from .output import DEFAULT_DIFF_PREVIEW_LINES, DEFAULT_PAGINATION_LINES
from .preflight import (
    agent_plan_command,
    agent_preflight_command,
    agent_undo_command,
)
from .resume import (
    _display_file_list,
    _display_review_header,
    _display_review_summary,
    _get_changed_files,
    _handle_review_choice,
    _load_suspension_data,
    _save_review_decisions,
    _show_file_diff,
    agent_resume_command,
    interactive_review_command,
    interactive_review_mode,
)
from .run import (
    _derive_policy_source,
    _display_recovery_guidance,
    _emit_readiness_payload,
    _execute_agent_task,
    _prepare_task,
    _require_plan_gate,
    _resolve_run_task,
    _resolve_selected_skills,
    _resolve_validation_profile,
    _run_post_validation,
    _save_git_sandbox_consent,
    _start_background_run,
    agent_run_task,
    show_interactive_diff,
)
from .runs import (
    _show_run_diff,
    agent_attach_command,
    agent_card_command,
    agent_daily_command,
    agent_run_show,
    agent_runs_commit_command,
    agent_runs_export,
    agent_runs_list,
    agent_runs_replay,
    agent_runs_trace,
    agent_status_command,
)
from .subagent_review import (
    agent_subagent_review_apply_command,
    agent_subagent_review_check_command,
    agent_subagent_review_list_command,
    agent_subagent_review_show_command,
)

__all__ = [
    # run.py
    'DEFAULT_DIFF_PREVIEW_LINES',
    'DEFAULT_PAGINATION_LINES',
    'agent_run_task',
    'show_interactive_diff',
    '_derive_policy_source',
    '_display_recovery_guidance',
    '_emit_readiness_payload',
    '_execute_agent_task',
    '_prepare_task',
    '_require_plan_gate',
    '_resolve_auto_compact',
    '_resolve_run_task',
    '_resolve_selected_skills',
    '_resolve_validation_profile',
    '_run_post_validation',
    '_save_git_sandbox_consent',
    '_start_background_run',
    # resume.py
    'agent_resume_command',
    'interactive_review_command',
    'interactive_review_mode',
    '_display_file_list',
    '_display_review_header',
    '_display_review_summary',
    '_get_changed_files',
    '_handle_review_choice',
    '_load_suspension_data',
    '_save_review_decisions',
    '_show_file_diff',
    # preflight.py
    'agent_preflight_command',
    'agent_plan_command',
    'agent_undo_command',
    # automation.py
    '_automation_draft_from_args',
    '_automation_health',
    '_automation_is_running',
    '_automation_tick',
    '_reconcile_automation_runs',
    '_run_automation_once',
    '_start_automation_background_run',
    'automation_add_command',
    'automation_delete_command',
    'automation_list_command',
    'automation_pause_command',
    'automation_promote_command',
    'automation_resume_command',
    'automation_run_command',
    'automation_serve_command',
    'automation_show_command',
    'automation_status_command',
    'automation_template_command',
    'automation_tick_command',
    # runs.py
    '_show_run_diff',
    'agent_attach_command',
    'agent_card_command',
    'agent_daily_command',
    'agent_run_show',
    'agent_runs_commit_command',
    'agent_runs_export',
    'agent_runs_list',
    'agent_runs_replay',
    'agent_runs_trace',
    'agent_status_command',
    # subagent_review.py
    'agent_subagent_review_apply_command',
    'agent_subagent_review_check_command',
    'agent_subagent_review_list_command',
    'agent_subagent_review_show_command',
    # approval.py
    'DEFAULT_SESSION_GRANT_TTL_HOURS',
    'cli_approval_handler',
    'make_cli_approval_handler',
    'make_cli_budget_prompt_handler',
    'run_result_payload',
    # experiment.py
    '_execute_parallel_experiment',
]
