"""Lazy export registry for teaagent public API (PERF-003)."""

from __future__ import annotations

import importlib
from typing import Any

# Maps public symbol -> (module_path, attribute_name)
_EXPORTS: dict[str, tuple[str, str]] = {
    'AIBOMComponent': ('teaagent.aibom', 'AIBOMComponent'),
    'AIBOMManifest': ('teaagent.aibom', 'AIBOMManifest'),
    'ANPAdapterError': ('teaagent.anp_adapter', 'ANPAdapterError'),
    'ANPBidirectionalRouter': ('teaagent.anp_adapter', 'ANPBidirectionalRouter'),
    'ANPDelegationResult': ('teaagent.anp_adapter', 'ANPDelegationResult'),
    'ANPGovernedInboundResult': ('teaagent.anp_adapter', 'ANPGovernedInboundResult'),
    'ANPGovernedService': ('teaagent.anp_adapter', 'ANPGovernedService'),
    'ANPInboundAdapter': ('teaagent.anp_adapter', 'ANPInboundAdapter'),
    'ANPOutboundClient': ('teaagent.anp_adapter', 'ANPOutboundClient'),
    'ANPRoutingResult': ('teaagent.anp_adapter', 'ANPRoutingResult'),
    'AgentCard': ('teaagent.agentcard', 'AgentCard'),
    'AgentRunner': ('teaagent.runner', 'AgentRunner'),
    'ApprovalPolicy': ('teaagent.policy', 'ApprovalPolicy'),
    'ApprovalRequest': ('teaagent.runner', 'ApprovalRequest'),
    'AuditEvent': ('teaagent.audit', 'AuditEvent'),
    'AuditLogger': ('teaagent.audit', 'AuditLogger'),
    'AutoModeConfig': ('teaagent.auto_mode', 'AutoModeConfig'),
    'AutoModeGuard': ('teaagent.auto_mode', 'AutoModeGuard'),
    'AutoModeLimitError': ('teaagent.auto_mode', 'AutoModeLimitError'),
    'BackendAdapter': ('teaagent.external_backends', 'BackendAdapter'),
    'BackendAdapterFactory': ('teaagent.external_backends', 'BackendAdapterFactory'),
    'BackendAdapterRegistry': ('teaagent.external_backends', 'BackendAdapterRegistry'),
    'BackendAdapterValidator': (
        'teaagent.external_backends',
        'BackendAdapterValidator',
    ),
    'BackendConfig': ('teaagent.external_backends', 'BackendConfig'),
    'BackendError': ('teaagent.external_backends', 'BackendError'),
    'BackendExecutionError': ('teaagent.external_backends', 'BackendExecutionError'),
    'BackendHealthCheckError': (
        'teaagent.external_backends',
        'BackendHealthCheckError',
    ),
    'BackendInitializationError': (
        'teaagent.external_backends',
        'BackendInitializationError',
    ),
    'BenchmarkBaseline': ('teaagent.benchmark', 'BenchmarkBaseline'),
    'BenchmarkResult': ('teaagent.benchmark', 'BenchmarkResult'),
    'BenchmarkSuite': ('teaagent.benchmark', 'BenchmarkSuite'),
    'CONFIG_KEYS': ('teaagent.config_loader', 'CONFIG_KEYS'),
    'CaseMetrics': ('teaagent.benchmark', 'CaseMetrics'),
    'ChainVerificationResult': ('teaagent.audit_chain', 'ChainVerificationResult'),
    'ChatAgentConfig': ('teaagent.chat_agent', 'ChatAgentConfig'),
    'ChildProcessCodeModeBackend': (
        'teaagent.code_mode',
        'ChildProcessCodeModeBackend',
    ),
    'CircuitBreakerConfig': ('teaagent.agentcard', 'CircuitBreakerConfig'),
    'ClarificationResult': ('teaagent.intent', 'ClarificationResult'),
    'CodeAnalysisConfig': ('teaagent.code_analysis', 'CodeAnalysisConfig'),
    'CodeModeResult': ('teaagent.code_mode', 'CodeModeResult'),
    'CodeModeSandbox': ('teaagent.code_mode', 'CodeModeSandbox'),
    'CodeParseBackend': ('teaagent.external_backends', 'CodeParseBackend'),
    'CodeReference': ('teaagent.code_analysis', 'CodeReference'),
    'CodeRelation': ('teaagent.code_analysis', 'CodeRelation'),
    'CodegraphMcpAdapter': ('teaagent.external_backends', 'CodegraphMcpAdapter'),
    'ConfigLayer': ('teaagent.config_loader', 'ConfigLayer'),
    'ConfigResolver': ('teaagent.config_loader', 'ConfigResolver'),
    'ContainerCodeModeBackend': ('teaagent.code_mode', 'ContainerCodeModeBackend'),
    'ContextCompactor': ('teaagent.context', 'ContextCompactor'),
    'CxCliAdapter': ('teaagent.external_backends', 'CxCliAdapter'),
    'DPoPValidationResult': ('teaagent.oauth21', 'DPoPValidationResult'),
    'DailyBrief': ('teaagent.daily', 'DailyBrief'),
    'DailyRecommendation': ('teaagent.daily', 'DailyRecommendation'),
    'Decision': ('teaagent.runner', 'Decision'),
    'DenyRule': ('teaagent.file_policy', 'DenyRule'),
    'DiffApprovalHandler': ('teaagent.approval_ui', 'DiffApprovalHandler'),
    'Document': ('teaagent.rag', 'Document'),
    'EvalCase': ('teaagent.eval', 'EvalCase'),
    'EvalReport': ('teaagent.eval', 'EvalReport'),
    'EventSpine': ('teaagent.runner', 'EventSpine'),
    'ExportManifest': ('teaagent.run_export', 'ExportManifest'),
    'FallbackKnowledgeBackend': (
        'teaagent.external_backends',
        'FallbackKnowledgeBackend',
    ),
    'FilePolicy': ('teaagent.file_policy', 'FilePolicy'),
    'FinalAnswer': ('teaagent.runner', 'FinalAnswer'),
    'GitToolConfig': ('teaagent.workspace_tools', 'GitToolConfig'),
    'GraphEdge': ('teaagent.graph_rag', 'GraphEdge'),
    'GraphQLiteConfig': ('teaagent.graphqlite_store', 'GraphQLiteConfig'),
    'GraphQLiteGraphStore': ('teaagent.graphqlite_store', 'GraphQLiteGraphStore'),
    'GraphQLitePersistentStore': (
        'teaagent.graphqlite_production',
        'GraphQLitePersistentStore',
    ),
    'GraphQLiteProductionConfig': (
        'teaagent.graphqlite_production',
        'GraphQLiteProductionConfig',
    ),
    'GraphQLiteRuntimeError': ('teaagent.graphqlite_store', 'GraphQLiteRuntimeError'),
    'GraphQLiteUnavailableError': (
        'teaagent.graphqlite_store',
        'GraphQLiteUnavailableError',
    ),
    'HAS_CRYPTOGRAPHY': ('teaagent.oauth21', 'HAS_CRYPTOGRAPHY'),
    'HAS_OTEL': ('teaagent.telemetry', 'HAS_OTEL'),
    'HAS_PLAYWRIGHT': ('teaagent.browser_tools', 'HAS_PLAYWRIGHT'),
    'HarnessHealthReport': ('teaagent.daily', 'HarnessHealthReport'),
    'Heartbeat': ('teaagent.heartbeat', 'Heartbeat'),
    'HookConfig': ('teaagent.hooks', 'HookConfig'),
    'HookError': ('teaagent.hooks', 'HookError'),
    'HookRegistry': ('teaagent.hooks', 'HookRegistry'),
    'HybridSearchBackend': ('teaagent.hybrid_search', 'HybridSearchBackend'),
    'InMemoryMetricsSink': ('teaagent.telemetry', 'InMemoryMetricsSink'),
    'InMemoryOAuthStore': ('teaagent.oauth21', 'InMemoryOAuthStore'),
    'InMemoryRetriever': ('teaagent.rag', 'InMemoryRetriever'),
    'IntentScore': ('teaagent.intent', 'IntentScore'),
    'InvalidClientError': ('teaagent.oauth21', 'InvalidClientError'),
    'InvalidDPoPError': ('teaagent.oauth21', 'InvalidDPoPError'),
    'InvalidGrantError': ('teaagent.oauth21', 'InvalidGrantError'),
    'JWTError': ('teaagent.oauth21', 'JWTError'),
    'KnowledgeGraph': ('teaagent.graph_rag', 'KnowledgeGraph'),
    'KnowledgeSearchBackend': ('teaagent.external_backends', 'KnowledgeSearchBackend'),
    'LLMConfigurationError': ('teaagent.llm', 'LLMConfigurationError'),
    'LLMHTTPError': ('teaagent.llm', 'LLMHTTPError'),
    'LLMMessage': ('teaagent.llm', 'LLMMessage'),
    'LLMProviderError': ('teaagent.llm', 'LLMProviderError'),
    'LLMRequest': ('teaagent.llm', 'LLMRequest'),
    'LLMResponse': ('teaagent.llm', 'LLMResponse'),
    'LLMResponseFormatError': ('teaagent.llm', 'LLMResponseFormatError'),
    'LSPServerConfig': ('teaagent.code_analysis', 'LSPServerConfig'),
    'LocalKnowledgeAdapter': ('teaagent.external_backends', 'LocalKnowledgeAdapter'),
    'MCPClientError': ('teaagent.mcp_client', 'MCPClientError'),
    'MCPHTTPClient': ('teaagent.mcp_client', 'MCPHTTPClient'),
    'MemoryCatalog': ('teaagent.memory', 'MemoryCatalog'),
    'MemoryEntry': ('teaagent.memory', 'MemoryEntry'),
    'MetricSnapshot': ('teaagent.telemetry', 'MetricSnapshot'),
    'ModelConformanceReport': ('teaagent.llm_conformance', 'ModelConformanceReport'),
    'ModelConformanceResult': ('teaagent.llm_conformance', 'ModelConformanceResult'),
    'ModelDecisionEngine': ('teaagent.chat_agent', 'ModelDecisionEngine'),
    'ModelRoute': ('teaagent.model_routing', 'ModelRoute'),
    'NotifyConfig': ('teaagent.notify', 'NotifyConfig'),
    'OAuth21AuthorizationServer': ('teaagent.oauth21', 'OAuth21AuthorizationServer'),
    'OAuth21Client': ('teaagent.oauth21', 'OAuth21Client'),
    'OAuth21ResourceServer': ('teaagent.oauth21', 'OAuth21ResourceServer'),
    'OAuth21TokenClaims': ('teaagent.oauth21', 'OAuth21TokenClaims'),
    'OAuth21TokenResponse': ('teaagent.oauth21', 'OAuth21TokenResponse'),
    'OAuthKeyRing': ('teaagent.oauth21', 'OAuthKeyRing'),
    'OAuthStore': ('teaagent.oauth21', 'OAuthStore'),
    'OTelAuditSink': ('teaagent.telemetry', 'OTelAuditSink'),
    'OTelMetricsSink': ('teaagent.telemetry', 'OTelMetricsSink'),
    'PackageNotFoundError': ('importlib.metadata', 'PackageNotFoundError'),
    'PermissionMode': ('teaagent.policy', 'PermissionMode'),
    'PluginLoadResult': ('teaagent.plugins', 'PluginLoadResult'),
    'PortabilityResult': ('teaagent.portability', 'PortabilityResult'),
    'PreflightReport': ('teaagent.preflight', 'PreflightReport'),
    'PromptBundle': ('teaagent.prompt', 'PromptBundle'),
    'ProviderConfig': ('teaagent.llm', 'ProviderConfig'),
    'ProviderProfile': ('teaagent.portability', 'ProviderProfile'),
    'QmdCliAdapter': ('teaagent.external_backends', 'QmdCliAdapter'),
    'QmdMcpAdapter': ('teaagent.external_backends', 'QmdMcpAdapter'),
    'ReadinessReport': ('teaagent.readiness', 'ReadinessReport'),
    'RedactionConfig': ('teaagent.redaction', 'RedactionConfig'),
    'ResolvedConfig': ('teaagent.config_loader', 'ResolvedConfig'),
    'RunBudget': ('teaagent.budget', 'RunBudget'),
    'RunCancelledError': ('teaagent.errors', 'RunCancelledError'),
    'RunEvent': ('teaagent.runner', 'RunEvent'),
    'RunEventType': ('teaagent.runner', 'RunEventType'),
    'audit_event_to_run_event_type': (
        'teaagent.runner',
        'audit_event_to_run_event_type',
    ),
    'read_run_events_from_audit': ('teaagent.runner', 'read_run_events_from_audit'),
    'read_run_events_from_jsonl': ('teaagent.runner', 'read_run_events_from_jsonl'),
    'RunRollup': ('teaagent.daily', 'RunRollup'),
    'RunStore': ('teaagent.run_store', 'RunStore'),
    'RunSummary': ('teaagent.run_store', 'RunSummary'),
    'SQLiteOAuthStore': ('teaagent.oauth21', 'SQLiteOAuthStore'),
    'SkillContent': ('teaagent.skill_loader', 'SkillContent'),
    'SkillLoadReport': ('teaagent.skill_loader', 'SkillLoadReport'),
    'SkillLoadSkipped': ('teaagent.skill_loader', 'SkillLoadSkipped'),
    'SkillLoadWarning': ('teaagent.skill_loader', 'SkillLoadWarning'),
    'SkillReviewResult': ('teaagent.skill_review', 'SkillReviewResult'),
    'StatelessMCPRequest': ('teaagent.stateless_mcp', 'StatelessMCPRequest'),
    'StatelessMCPResponse': ('teaagent.stateless_mcp', 'StatelessMCPResponse'),
    'SubagentDef': ('teaagent.subagents', 'SubagentDef'),
    'SubagentManager': ('teaagent.subagents', 'SubagentManager'),
    'SubagentSession': ('teaagent.subagents', 'SubagentSession'),
    'TelemetryConfig': ('teaagent.telemetry', 'TelemetryConfig'),
    'TelemetryNotAvailable': ('teaagent.telemetry', 'TelemetryNotAvailable'),
    'TokenBudgetReport': ('teaagent.daily', 'TokenBudgetReport'),
    'ToolAnnotations': ('teaagent.tools', 'ToolAnnotations'),
    'ToolRateLimit': ('teaagent.tools', 'ToolRateLimit'),
    'ToolRegistry': ('teaagent.tools', 'ToolRegistry'),
    'ToolRegistryBuilder': ('teaagent.workspace_tools', 'ToolRegistryBuilder'),
    'ToolRequest': ('teaagent.runner', 'ToolRequest'),
    'TraceRecorder': ('teaagent.trace', 'TraceRecorder'),
    'TraceparentError': ('teaagent.a2a_trace', 'TraceparentError'),
    'TracingHTTPTransport': ('teaagent.telemetry', 'TracingHTTPTransport'),
    'UltraworkStore': ('teaagent.ultrawork', 'UltraworkStore'),
    'UndoJournal': ('teaagent.run_undo', 'UndoJournal'),
    'UndoResult': ('teaagent.run_undo', 'UndoResult'),
    'UnsafeCodeError': ('teaagent.code_mode', 'UnsafeCodeError'),
    'WebhookAuditSink': ('teaagent.webhook_sink', 'WebhookAuditSink'),
    'WorkerRecord': ('teaagent.ultrawork', 'WorkerRecord'),
    'WorkspaceToolConfig': ('teaagent.workspace_tools', 'WorkspaceToolConfig'),
    'agentic_retrieve': ('teaagent.rag', 'agentic_retrieve'),
    'assemble_agent_prompt': ('teaagent.prompt', 'assemble_agent_prompt'),
    'assess_managed_agent_readiness': (
        'teaagent.readiness',
        'assess_managed_agent_readiness',
    ),
    'assess_provider_portability': (
        'teaagent.portability',
        'assess_provider_portability',
    ),
    'available_providers': ('teaagent.llm', 'available_providers'),
    'build_aibom': ('teaagent.aibom', 'build_aibom'),
    'build_daily_brief': ('teaagent.daily', 'build_daily_brief'),
    'build_mcp_http_server': ('teaagent.mcp_http', 'build_mcp_http_server'),
    'build_task_spec': ('teaagent.intent', 'build_task_spec'),
    'build_workspace_tool_registry': (
        'teaagent.workspace_tools',
        'build_workspace_tool_registry',
    ),
    'check_graphqlite_runtime': (
        'teaagent.graphqlite_store',
        'check_graphqlite_runtime',
    ),
    'check_llm_configuration': ('teaagent.llm', 'check_llm_configuration'),
    'clarify_task': ('teaagent.intent', 'clarify_task'),
    'classify_task': ('teaagent.model_routing', 'classify_task'),
    'compute_event_hash': ('teaagent.audit_chain', 'compute_event_hash'),
    'compute_jwk_thumbprint': ('teaagent.oauth21', 'compute_jwk_thumbprint'),
    'compute_s256_challenge': ('teaagent.oauth21', 'compute_s256_challenge'),
    'configure_metrics': ('teaagent.telemetry', 'configure_metrics'),
    'configure_telemetry': ('teaagent.telemetry', 'configure_telemetry'),
    'create_jwt': ('teaagent.oauth21', 'create_jwt'),
    'create_llm_adapter': ('teaagent.llm', 'create_llm_adapter'),
    'decode_jwt_unsafe': ('teaagent.oauth21', 'decode_jwt_unsafe'),
    'discover_skill_search_dirs': (
        'teaagent.skill_loader',
        'discover_skill_search_dirs',
    ),
    'ensure_sqlite_extension_loading': (
        'teaagent.graphqlite_store',
        'ensure_sqlite_extension_loading',
    ),
    'execute_code_mode': ('teaagent.code_mode', 'execute_code_mode'),
    'export_run': ('teaagent.run_export', 'export_run'),
    'extract_tree_sitter_relations': (
        'teaagent.code_analysis',
        'extract_tree_sitter_relations',
    ),
    'fire_notification': ('teaagent.notify', 'fire_notification'),
    'format_check_hook': ('teaagent.hooks', 'format_check_hook'),
    'generate_code_verifier': ('teaagent.oauth21', 'generate_code_verifier'),
    'generate_traceparent': ('teaagent.a2a_trace', 'generate_traceparent'),
    'get_code_parse_backend': ('teaagent.external_backends', 'get_code_parse_backend'),
    'get_default_registry': ('teaagent.external_backends', 'get_default_registry'),
    'get_hybrid_backend': ('teaagent.hybrid_search', 'get_hybrid_backend'),
    'get_knowledge_backend': ('teaagent.external_backends', 'get_knowledge_backend'),
    'graph_retrieve': ('teaagent.graph_rag', 'graph_retrieve'),
    'handle_mcp_request': ('teaagent.mcp_server', 'handle_mcp_request'),
    'handle_stateless_tool_request': (
        'teaagent.stateless_mcp',
        'handle_stateless_tool_request',
    ),
    'import_run': ('teaagent.run_export', 'import_run'),
    'ingest_code_relations_to_graph': (
        'teaagent.code_analysis',
        'ingest_code_relations_to_graph',
    ),
    'lint_check_hook': ('teaagent.hooks', 'lint_check_hook'),
    'load_file_policy': ('teaagent.file_policy', 'load_file_policy'),
    'load_plugins': ('teaagent.plugins', 'load_plugins'),
    'load_skills': ('teaagent.skill_loader', 'load_skills'),
    'load_skills_with_report': ('teaagent.skill_loader', 'load_skills_with_report'),
    'load_workspace_config': ('teaagent.config_loader', 'load_workspace_config'),
    'managed_runtime_capabilities': (
        'teaagent.managed_runtime',
        'managed_runtime_capabilities',
    ),
    'managed_runtime_context': ('teaagent.managed_runtime', 'managed_runtime_context'),
    'parse_model_decision': ('teaagent.prompt', 'parse_model_decision'),
    'parse_permission_mode': ('teaagent.policy', 'parse_permission_mode'),
    'parse_traceparent': ('teaagent.a2a_trace', 'parse_traceparent'),
    'post_lint_check_hook': ('teaagent.hooks', 'post_lint_check_hook'),
    'preflight': ('teaagent.preflight', 'preflight'),
    'register_browser_tools': ('teaagent.browser_tools', 'register_browser_tools'),
    'register_code_analysis_tools': (
        'teaagent.code_analysis',
        'register_code_analysis_tools',
    ),
    'register_code_parse_backend': (
        'teaagent.external_backends',
        'register_code_parse_backend',
    ),
    'register_audit_consumer': ('teaagent.runner', 'register_audit_consumer'),
    'register_git_tools': ('teaagent.workspace_tools', 'register_git_tools'),
    'register_hybrid_backend': ('teaagent.hybrid_search', 'register_hybrid_backend'),
    'register_knowledge_backend': (
        'teaagent.external_backends',
        'register_knowledge_backend',
    ),
    'register_mcp_tools': ('teaagent.mcp_tool_adapter', 'register_mcp_tools'),
    'register_subagent_tool': ('teaagent.chat_agent', 'register_subagent_tool'),
    'register_workspace_tools': (
        'teaagent.workspace_tools',
        'register_workspace_tools',
    ),
    'render_html_report': ('teaagent.eval_report', 'render_html_report'),
    'review_skill': ('teaagent.skill_review', 'review_skill'),
    'route_model': ('teaagent.model_routing', 'route_model'),
    'run_benchmark': ('teaagent.benchmark', 'run_benchmark'),
    'run_chat_agent': ('teaagent.chat_agent', 'run_chat_agent'),
    'run_eval': ('teaagent.eval', 'run_eval'),
    'run_model_conformance': ('teaagent.llm_conformance', 'run_model_conformance'),
    'run_tests_hook': ('teaagent.hooks', 'run_tests_hook'),
    'serve_mcp_http': ('teaagent.mcp_http', 'serve_mcp_http'),
    'serve_mcp_stdio': ('teaagent.mcp_server', 'serve_mcp_stdio'),
    'shell_command_hook': ('teaagent.hooks', 'shell_command_hook'),
    'skills_to_prompt_section': ('teaagent.skill_loader', 'skills_to_prompt_section'),
    'verify_audit_chain': ('teaagent.audit_chain', 'verify_audit_chain'),
    'verify_jwt': ('teaagent.oauth21', 'verify_jwt'),
}

_CACHE: dict[str, Any] = {}


def lazy_getattr(name: str) -> Any:
    if name in _CACHE:
        return _CACHE[name]
    spec = _EXPORTS.get(name)
    if spec is None:
        raise AttributeError(f"module 'teaagent' has no attribute {name!r}")
    module_path, attr = spec
    module = importlib.import_module(module_path)
    value = getattr(module, attr)
    _CACHE[name] = value
    return value


def lazy_dir() -> list[str]:
    return sorted({'__version__', *__all__names()})


def __all__names() -> set[str]:
    return set(_EXPORTS)
