"""Generate a deterministic Markdown inventory of docs/ (DOW-021).

The output is secondary to the curated front door at docs/INDEX.md.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_OUTPUT = _REPO_ROOT / 'docs' / 'generated' / 'docs-inventory.md'
_DOCS_ROOT = _REPO_ROOT / 'docs'

_INVENTORY_BANNER = """# Documentation Inventory (Generated)

> **Not current truth.** This file is a deterministic catalog only.
> For the curated front door, use [docs/INDEX.md](../INDEX.md).

Generated by `python3 scripts/generate_docs_inventory.py`.
Do not edit this file manually — regenerate instead.
"""

# Constitution tier: exactly these docs (plus README if in scope)
# Paths are relative to docs_root
_CONSTITUTION_DOCS = {
    'product-contract.md',
    'architecture.md',
    'terminology.md',
    'acceptance.md',
    'roadmap-status.md',
    'agent-contribution-contract.md',
    'strategy/harness-first-direction-2026-06-13.md',
    'governance-compliance.md',
}

# Date pattern for archive-tier docs (any doc with YYYY-MM-DD in filename)
_ARCHIVE_DATE_PATTERN = re.compile(r'\d{4}-\d{2}-\d{2}')

# Dated docs that remain current truth (not archive despite date in filename).
_WORKING_CURRENT_TRUTH_DOCS = {
    'analysis/active-findings-status-ledger-2026-06-06.md',
}


def _relative_doc_path(path: Path, docs_root: Path) -> str:
    return path.relative_to(docs_root).as_posix()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()[:12]


def _classify_tier(rel_path: str) -> str:
    """Classify a doc into constitution, archive, or working tier.

    - Constitution: exactly the constitution docs listed above.
    - Working (current truth): explicit override list for dated active ledgers.
    - Archive: any other doc with YYYY-MM-DD date pattern in filename.
    - Working: everything else.
    """
    if rel_path in _CONSTITUTION_DOCS:
        return 'constitution'
    if rel_path in _WORKING_CURRENT_TRUTH_DOCS:
        return 'working'
    if _ARCHIVE_DATE_PATTERN.search(rel_path):
        return 'archive'
    return 'working'


def generate_docs_inventory(
    *,
    docs_root: Path = _DOCS_ROOT,
    output_path: Path = _DEFAULT_OUTPUT,
) -> str:
    if not docs_root.is_dir():
        raise ValueError(f'docs root not found: {docs_root}')

    output_resolved = output_path.resolve()
    markdown_files = sorted(
        (
            path
            for path in docs_root.rglob('*.md')
            if path.is_file() and path.resolve() != output_resolved
        ),
        key=lambda path: _relative_doc_path(path, docs_root).lower(),
    )

    lines = [
        _INVENTORY_BANNER.strip(),
        '',
        f'**Markdown files:** {len(markdown_files)}',
        '',
        '| Path | Tier | Bytes | SHA256 (12) |',
        '| --- | --- | ---: | --- |',
    ]

    for path in markdown_files:
        stat = path.stat()
        rel = _relative_doc_path(path, docs_root)
        tier = _classify_tier(rel)
        lines.append(f'| `{rel}` | {tier} | {stat.st_size} | `{_file_sha256(path)}` |')

    lines.append('')
    return '\n'.join(lines)


def write_docs_inventory(
    *,
    docs_root: Path = _DOCS_ROOT,
    output_path: Path = _DEFAULT_OUTPUT,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_docs_inventory(docs_root=docs_root, output_path=output_path),
        encoding='utf-8',
    )
    return output_path


def check_docs_inventory(
    *,
    docs_root: Path = _DOCS_ROOT,
    output_path: Path = _DEFAULT_OUTPUT,
) -> list[str]:
    expected = generate_docs_inventory(
        docs_root=docs_root,
        output_path=output_path,
    )
    if not output_path.is_file():
        try:
            rel = output_path.relative_to(_REPO_ROOT)
        except ValueError:
            rel = output_path
        return [f'{rel} missing; run: python3 scripts/generate_docs_inventory.py']
    actual = output_path.read_text(encoding='utf-8')
    if actual == expected:
        return []
    try:
        rel = output_path.relative_to(_REPO_ROOT)
    except ValueError:
        rel = output_path
    return [f'{rel} is out of date; run: python3 scripts/generate_docs_inventory.py']


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description='Generate deterministic docs/ inventory (secondary to INDEX.md).'
    )
    parser.add_argument(
        '--output',
        default=str(_DEFAULT_OUTPUT),
        help='Output markdown path (default: docs/generated/docs-inventory.md).',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Fail if tracked inventory is stale without writing.',
    )
    parser.add_argument('--docs-root', default=str(_DOCS_ROOT))
    args = parser.parse_args(argv)

    docs_root = Path(args.docs_root)
    output_path = Path(args.output)

    if args.check:
        errors = check_docs_inventory(docs_root=docs_root, output_path=output_path)
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        print('Docs inventory check passed.')
        return 0

    written = write_docs_inventory(docs_root=docs_root, output_path=output_path)
    print(f'wrote {written}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
