#!/usr/bin/env python3
"""Generate docs/architecture/module-dependencies.md from import graph."""

from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / 'teaagent'
OUT = ROOT / 'docs' / 'architecture' / 'module-dependencies.md'


def module_imports(path: Path) -> set[str]:
    try:
        tree = ast.parse(path.read_text(encoding='utf-8'), filename=str(path))
    except SyntaxError:
        return set()
    mods: set[str] = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.ImportFrom)
            and node.module
            and node.module.startswith('teaagent.')
        ):
            mods.add(node.module)
    return mods


def main() -> None:
    edges: dict[str, set[str]] = defaultdict(set)
    for path in sorted(PKG.rglob('*.py')):
        mod = 'teaagent.' + str(path.relative_to(PKG)).replace('/', '.').removesuffix(
            '.py'
        )
        if mod.endswith('.__init__'):
            mod = mod[: -len('.__init__')]
        for dep in module_imports(path):
            edges[mod].add(dep)

    lines = [
        '# Module Dependencies',
        '',
        '> Auto-generated by `scripts/generate_module_deps.py`. Do not edit by hand.',
        '',
        '## Hot-path modules (most outbound imports)',
        '',
    ]
    ranked = sorted(edges.items(), key=lambda kv: len(kv[1]), reverse=True)[:25]
    for mod, deps in ranked:
        lines.append(f'- `{mod}` → {len(deps)} teaagent imports')

    lines.extend(['', '## Sample dependency edges', ''])
    for mod, deps in ranked[:10]:
        sample = ', '.join(f'`{d}`' for d in sorted(deps)[:8])
        lines.append(f'### `{mod}`')
        lines.append(sample or '_none_')
        lines.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
