#!/usr/bin/env zsh
# TeaAgent Provider Environment Template
# Source this file to set provider defaults for your shell profile.
#
# Recommended layering:
#   1) Global defaults in ~/.teaagent/providers_env.zsh (this file)
#   2) Per-project overrides in <repo>/.teaagent/env (generated by wizards)
#      Load per-project file after this one when needed.
#
# Usage:
#   1. Copy this file: cp scripts/providers_env.zsh ~/.teaagent/providers_env.zsh
#   2. Edit it to fill in your defaults
#   3. Add to your ~/.zshrc:
#        source ~/.teaagent/providers_env.zsh
#   4. For project overrides:
#        source .teaagent/env

# --- Anthropic (Claude) ---
# Get your key at: https://console.anthropic.com/settings/keys
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

# --- OpenAI (GPT) ---
# Get your key at: https://platform.openai.com/api-keys
export OPENAI_API_KEY="${OPENAI_API_KEY:-}"

# --- Google Gemini ---
# Get your key at: https://aistudio.google.com/apikey
export GEMINI_API_KEY="${GEMINI_API_KEY:-}"

# --- OpenRouter ---
# Get your key at: https://openrouter.ai/settings/keys
export OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"

# --- OpenCodeZen ---
# Get your key at: https://opencode.ai/settings
export OPENCODEZEN_API_KEY="${OPENCODEZEN_API_KEY:-}"

# --- Cloudflare Workers AI ---
# Get your API token at: https://dash.cloudflare.com/profile/api-tokens
export CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
# Account ID used by default Workers AI direct endpoint template.
export CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-}"

# --- Optional: Custom base URLs (uncomment to override) ---
# export ANTHROPIC_BASE_URL="https://api.anthropic.com/v1"
# export OPENAI_BASE_URL="https://api.openai.com/v1"
# export GEMINI_BASE_URL="https://generativelanguage.googleapis.com/v1beta"
# export OPENROUTER_BASE_URL="https://openrouter.ai/api/v1"
# export OPENCODEZEN_BASE_URL="https://opencode.ai/zen/go/v1"
# export WORKERS_AI_BASE_URL="https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1"
# Optional when AI Gateway authenticated mode is enabled:
# export WORKERS_AI_EXTRA_HEADERS='{"cf-aig-authorization":"Bearer <gateway_token>"}'

# --- Provider-specific model overrides ---
# Uncomment and edit to override the default model for a provider:
# export CLAUDE_MODEL="claude-3-5-sonnet-latest"
# export GPT_MODEL="gpt-4o-mini"
# export GEMINI_MODEL="gemini-1.5-flash"
# export OPENROUTER_MODEL="openai/gpt-4o-mini"
# export OPENCODEZEN_GO_MODEL="deepseek-v4-flash"
# export WORKERS_AI_MODEL="@cf/meta/llama-3.1-8b-instruct"

# --- Quick verification ---
# Run after sourcing:
#   teaagent doctor providers
#   teaagent doctor aigateway
